name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 19.3.0
          cache: pnpm
      - name: Restore VitePress cache
        uses: actions/cache@v3
        with:
          path: .vitepress/cache
          key: ${{ runner.os }}-vitepress-cache-v1
          restore-keys: |
            ${{ runner.os }}-vitepress-cache-v1
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run docs:build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
